"""users details

Revision ID: 08e26d8562e2
Revises: 060ecb1defde
Create Date: 2020-11-17 11:05:31.088936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08e26d8562e2'
down_revision = '060ecb1defde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('users_table', sa.Column('Ano', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('CEP', sa.String(length=32), nullable=True))
    op.add_column('users_table', sa.Column('Cidade', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('Dia', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('Endereco1', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('Endereco2', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('Estado', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('Mes', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('Pais', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('Sobre_mim', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('genero', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_table_genero'), 'users_table', ['genero'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_table_genero'), table_name='users_table')
    op.drop_column('users_table', 'genero')
    op.drop_column('users_table', 'Sobre_mim')
    op.drop_column('users_table', 'Pais')
    op.drop_column('users_table', 'Mes')
    op.drop_column('users_table', 'Estado')
    op.drop_column('users_table', 'Endereco2')
    op.drop_column('users_table', 'Endereco1')
    op.drop_column('users_table', 'Dia')
    op.drop_column('users_table', 'Cidade')
    op.drop_column('users_table', 'CEP')
    op.drop_column('users_table', 'Ano')
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
