"""inicial

Revision ID: 5378bdcd0d01
Revises: 
Create Date: 2020-09-21 13:53:39.794014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5378bdcd0d01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msgs_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msgs_table_timestamp'), 'msgs_table', ['timestamp'], unique=False)
    op.create_table('UsersMsgs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('msg_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['msgs_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('users_table', 'msgs_enviadas_id')
    op.drop_column('users_table', 'msgs_recebidas_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('msgs_recebidas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users_table', sa.Column('msgs_enviadas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_table('UsersMsgs')
    op.drop_index(op.f('ix_msgs_table_timestamp'), table_name='msgs_table')
    op.drop_table('msgs_table')
    # ### end Alembic commands ###
