"""minusculas

Revision ID: c940ce0e2ecd
Revises: 0b1b9b3c6ead
Create Date: 2020-11-18 15:33:11.408027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c940ce0e2ecd'
down_revision = '0b1b9b3c6ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('users_table', sa.Column('ano', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('cep', sa.String(length=32), nullable=True))
    op.add_column('users_table', sa.Column('cidade', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('dia', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('endereco1', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('endereco2', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('endereco3', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('estado', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('mes', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('pais', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('sobre_mim', sa.String(length=128), nullable=True))
    op.drop_column('users_table', 'Cidade')
    op.drop_column('users_table', 'Endereco1')
    op.drop_column('users_table', 'CEP')
    op.drop_column('users_table', 'Estado')
    op.drop_column('users_table', 'Ano')
    op.drop_column('users_table', 'Sobre_mim')
    op.drop_column('users_table', 'Pais')
    op.drop_column('users_table', 'Endereco3')
    op.drop_column('users_table', 'Dia')
    op.drop_column('users_table', 'Mes')
    op.drop_column('users_table', 'Endereco2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('Endereco2', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users_table', sa.Column('Mes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users_table', sa.Column('Dia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users_table', sa.Column('Endereco3', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users_table', sa.Column('Pais', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users_table', sa.Column('Sobre_mim', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users_table', sa.Column('Ano', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users_table', sa.Column('Estado', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users_table', sa.Column('CEP', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('users_table', sa.Column('Endereco1', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users_table', sa.Column('Cidade', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('users_table', 'sobre_mim')
    op.drop_column('users_table', 'pais')
    op.drop_column('users_table', 'mes')
    op.drop_column('users_table', 'estado')
    op.drop_column('users_table', 'endereco3')
    op.drop_column('users_table', 'endereco2')
    op.drop_column('users_table', 'endereco1')
    op.drop_column('users_table', 'dia')
    op.drop_column('users_table', 'cidade')
    op.drop_column('users_table', 'cep')
    op.drop_column('users_table', 'ano')
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
