"""empty message

Revision ID: 02a0548a3aa2
Revises: c11e0a9a4449
Create Date: 2020-09-18 15:41:37.445570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02a0548a3aa2'
down_revision = 'c11e0a9a4449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('destination_id_2', table_name='msgs_table')
    op.drop_index('sender_id_2', table_name='msgs_table')
    op.create_foreign_key(None, 'msgs_table', 'users_table', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'msgs_table', 'users_table', ['destination_id'], ['id'])
    op.alter_column('orgs_table', 'status',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('users_table', 'msgs_enviadas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users_table', 'msgs_recebidas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'users_table', 'msgs_table', ['msgs_recebidas_id'], ['id'])
    op.create_foreign_key(None, 'users_table', 'msgs_table', ['msgs_enviadas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.alter_column('users_table', 'msgs_recebidas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('users_table', 'msgs_enviadas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('orgs_table', 'status',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'msgs_table', type_='foreignkey')
    op.drop_constraint(None, 'msgs_table', type_='foreignkey')
    op.create_index('sender_id_2', 'msgs_table', ['sender_id'], unique=False)
    op.create_index('destination_id_2', 'msgs_table', ['destination_id'], unique=False)
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
