"""proj+

Revision ID: 3e96fe9ca88b
Revises: a0151b912e4d
Create Date: 2020-06-30 20:55:00.401548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e96fe9ca88b'
down_revision = 'a0151b912e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projs_table', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projs_table', 'status')
    # ### end Alembic commands ###
