"""simplificando

Revision ID: 41ce8db27f71
Revises: 9414388c5b70
Create Date: 2020-07-03 00:27:33.363293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41ce8db27f71'
down_revision = '9414388c5b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrgsProjs',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs_table.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], )
    )
    op.create_table('OrgsUsers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], )
    )
    op.create_table('UsersProjs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], )
    )
    op.create_table('UsersTasks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], )
    )
    op.drop_table('userstasks_table')
    op.drop_table('projsicons_table')
    op.drop_table('orgsprojs_table')
    op.drop_table('usersprojs_table')
    op.drop_table('orgsusers_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgsusers_table',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('org_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('adesao', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('funcao', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs_table.id'], name='orgsusers_table_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='orgsusers_table_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'org_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('usersprojs_table',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('proj_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('adesao', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('funcao', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], name='usersprojs_table_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='usersprojs_table_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'proj_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('orgsprojs_table',
    sa.Column('org_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('proj_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('relacao', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs_table.id'], name='orgsprojs_table_ibfk_1'),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], name='orgsprojs_table_ibfk_2'),
    sa.PrimaryKeyConstraint('org_id', 'proj_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('projsicons_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('proj_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('icon_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('relacao', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icons_table.id'], name='projsicons_table_ibfk_1'),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], name='projsicons_table_ibfk_2'),
    sa.PrimaryKeyConstraint('id', 'proj_id', 'icon_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('userstasks_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('relacao', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks_table.id'], name='userstasks_table_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='userstasks_table_ibfk_2'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'task_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('UsersTasks')
    op.drop_table('UsersProjs')
    op.drop_table('OrgsUsers')
    op.drop_table('OrgsProjs')
    # ### end Alembic commands ###
