"""avatar5

Revision ID: 4e69bf7d4406
Revises: 8e044b3c553e
Create Date: 2020-07-03 20:33:48.471063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e69bf7d4406'
down_revision = '8e044b3c553e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_table_ibfk_1', 'users_table', type_='foreignkey')
    op.create_foreign_key(None, 'users_table', 'icons_table', ['avatar_id'], ['id'])
    op.drop_column('users_table', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('avatar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.create_foreign_key('users_table_ibfk_1', 'users_table', 'icons_table', ['avatar'], ['id'])
    op.drop_column('users_table', 'avatar_id')
    # ### end Alembic commands ###
