"""files

Revision ID: 4ef929508e50
Revises: c86f62955b06
Create Date: 2020-07-08 10:39:04.790382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef929508e50'
down_revision = 'c86f62955b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icons_table', sa.Column('criador_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'icons_table', 'users_table', ['criador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'icons_table', type_='foreignkey')
    op.drop_column('icons_table', 'criador_id')
    # ### end Alembic commands ###
