"""avatar3

Revision ID: 52f28647ca08
Revises: fddacf80ed28
Create Date: 2020-07-03 19:15:58.693162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52f28647ca08'
down_revision = 'fddacf80ed28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('icons_table_ibfk_1', 'icons_table', type_='foreignkey')
    op.drop_column('icons_table', 'user_id')
    op.add_column('users_table', sa.Column('avatar', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users_table', 'users_table', ['avatar'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.drop_column('users_table', 'avatar')
    op.add_column('icons_table', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('icons_table_ibfk_1', 'icons_table', 'users_table', ['user_id'], ['id'])
    # ### end Alembic commands ###
