"""org resp

Revision ID: 6801e377b843
Revises: dba00936da75
Create Date: 2020-07-06 19:12:58.204334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6801e377b843'
down_revision = 'dba00936da75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_table', sa.Column('responsavel', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orgs_table', 'users_table', ['responsavel'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orgs_table', type_='foreignkey')
    op.drop_column('orgs_table', 'responsavel')
    # ### end Alembic commands ###
