"""tasks

Revision ID: 68b7bc38d8ef
Revises: b03593a85e7f
Create Date: 2020-07-02 14:53:01.848765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b7bc38d8ef'
down_revision = 'b03593a85e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.Column('progresso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userstasks_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('relacao', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'task_id')
    )
    op.add_column('projs_table', sa.Column('icon', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('avatar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'avatar')
    op.drop_column('projs_table', 'icon')
    op.drop_table('userstasks_table')
    op.drop_table('tasks_table')
    # ### end Alembic commands ###
