"""files2

Revision ID: 7c485e522141
Revises: 4ef929508e50
Create Date: 2020-07-08 11:19:09.609976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c485e522141'
down_revision = '4ef929508e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('icons_table_ibfk_1', 'icons_table', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('icons_table_ibfk_1', 'icons_table', 'users_table', ['criador_id'], ['id'])
    # ### end Alembic commands ###
