"""avatar4

Revision ID: 8e044b3c553e
Revises: 52f28647ca08
Create Date: 2020-07-03 20:12:33.554811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e044b3c553e'
down_revision = '52f28647ca08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_table_ibfk_1', 'users_table', type_='foreignkey')
    op.create_foreign_key(None, 'users_table', 'icons_table', ['avatar'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.create_foreign_key('users_table_ibfk_1', 'users_table', 'users_table', ['avatar'], ['id'])
    # ### end Alembic commands ###
