"""visibilidade

Revision ID: 9414388c5b70
Revises: 68b7bc38d8ef
Create Date: 2020-07-02 19:27:18.641942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9414388c5b70'
down_revision = '68b7bc38d8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projs_table', sa.Column('visibilidade', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projs_table', 'visibilidade')
    # ### end Alembic commands ###
