"""2

Revision ID: a0151b912e4d
Revises: 
Create Date: 2020-06-30 01:37:13.668737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0151b912e4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projsicons_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proj_id', sa.Integer(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('relacao', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icons_table.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], ),
    sa.PrimaryKeyConstraint('id', 'proj_id', 'icon_id')
    )
    op.add_column('icons_table', sa.Column('tipo', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icons_table', 'tipo')
    op.drop_table('projsicons_table')
    # ### end Alembic commands ###
