"""responsavel

Revision ID: b03593a85e7f
Revises: 3e96fe9ca88b
Create Date: 2020-06-30 23:23:53.061482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03593a85e7f'
down_revision = '3e96fe9ca88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projs_table', sa.Column('responsavel', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projs_table', 'responsavel')
    # ### end Alembic commands ###
