"""logo

Revision ID: b59300f50c40
Revises: 4e69bf7d4406
Create Date: 2020-07-06 11:34:32.882722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59300f50c40'
down_revision = '4e69bf7d4406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_table', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orgs_table', 'icons_table', ['logo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orgs_table', type_='foreignkey')
    op.drop_column('orgs_table', 'logo_id')
    # ### end Alembic commands ###
