"""inclui msgs

Revision ID: c11e0a9a4449
Revises: 7c485e522141
Create Date: 2020-09-18 13:17:23.438703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c11e0a9a4449'
down_revision = '7c485e522141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'OrgsProjs', 'projs_table', ['proj_id'], ['id'])
    op.create_foreign_key(None, 'OrgsProjs', 'orgs_table', ['org_id'], ['id'])
    op.add_column('OrgsUsers', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('UsersProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('UsersProjs', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'UsersProjs', 'users_table', ['user_id'], ['id'])
    op.create_foreign_key(None, 'UsersProjs', 'projs_table', ['proj_id'], ['id'])
    op.add_column('UsersTasks', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('msgs_table', 'body',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('msgs_table', 'destination_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('msgs_table', 'sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('msgs_table', 'timestamp',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('msgs_table', 'tipo',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_msgs_table_timestamp'), 'msgs_table', ['timestamp'], unique=False)
    op.drop_index('destination_id', table_name='msgs_table')
    op.drop_index('destination_id_2', table_name='msgs_table')
    op.drop_index('sender_id', table_name='msgs_table')
    op.drop_index('sender_id_2', table_name='msgs_table')
    op.drop_constraint('msgs_table_ibfk_2', 'msgs_table', type_='foreignkey')
    op.drop_constraint('msgs_table_ibfk_1', 'msgs_table', type_='foreignkey')
    op.create_foreign_key(None, 'msgs_table', 'users_table', ['destination_id'], ['id'])
    op.create_foreign_key(None, 'msgs_table', 'users_table', ['sender_id'], ['id'])
    op.alter_column('orgs_table', 'status',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('users_table', 'msgs_enviadas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users_table', 'msgs_recebidas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'users_table', 'msgs_table', ['msgs_enviadas_id'], ['id'])
    op.create_foreign_key(None, 'users_table', 'msgs_table', ['msgs_recebidas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.alter_column('users_table', 'msgs_recebidas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('users_table', 'msgs_enviadas_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('orgs_table', 'status',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'msgs_table', type_='foreignkey')
    op.drop_constraint(None, 'msgs_table', type_='foreignkey')
    op.create_foreign_key('msgs_table_ibfk_1', 'msgs_table', 'users_table', ['sender_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('msgs_table_ibfk_2', 'msgs_table', 'users_table', ['destination_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('sender_id_2', 'msgs_table', ['sender_id'], unique=False)
    op.create_index('sender_id', 'msgs_table', ['sender_id'], unique=True)
    op.create_index('destination_id_2', 'msgs_table', ['destination_id'], unique=False)
    op.create_index('destination_id', 'msgs_table', ['destination_id'], unique=True)
    op.drop_index(op.f('ix_msgs_table_timestamp'), table_name='msgs_table')
    op.alter_column('msgs_table', 'tipo',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('msgs_table', 'timestamp',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('msgs_table', 'sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('msgs_table', 'destination_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('msgs_table', 'body',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('UsersTasks', 'id')
    op.drop_constraint(None, 'UsersProjs', type_='foreignkey')
    op.drop_constraint(None, 'UsersProjs', type_='foreignkey')
    op.alter_column('UsersProjs', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('UsersProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('OrgsUsers', 'id')
    op.drop_constraint(None, 'OrgsProjs', type_='foreignkey')
    op.drop_constraint(None, 'OrgsProjs', type_='foreignkey')
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
