"""org projs tasks

Revision ID: c86f62955b06
Revises: fde401d2733c
Create Date: 2020-07-06 20:39:15.344401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c86f62955b06'
down_revision = 'fde401d2733c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_table', sa.Column('responsavel_id', sa.Integer(), nullable=True))
    op.drop_constraint('orgs_table_ibfk_2', 'orgs_table', type_='foreignkey')
    op.create_foreign_key(None, 'orgs_table', 'users_table', ['responsavel_id'], ['id'])
    op.drop_column('orgs_table', 'respons')
    op.add_column('projs_table', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('projs_table', sa.Column('responsavel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projs_table', 'icons_table', ['icon_id'], ['id'])
    op.create_foreign_key(None, 'projs_table', 'users_table', ['responsavel_id'], ['id'])
    op.drop_column('projs_table', 'responsavel')
    op.drop_column('projs_table', 'icon')
    op.create_foreign_key(None, 'tasks_table', 'users_table', ['responsavel_id'], ['id'])
    op.create_foreign_key(None, 'tasks_table', 'projs_table', ['proj_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_table', type_='foreignkey')
    op.drop_constraint(None, 'tasks_table', type_='foreignkey')
    op.add_column('projs_table', sa.Column('icon', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('projs_table', sa.Column('responsavel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projs_table', type_='foreignkey')
    op.drop_constraint(None, 'projs_table', type_='foreignkey')
    op.drop_column('projs_table', 'responsavel_id')
    op.drop_column('projs_table', 'icon_id')
    op.add_column('orgs_table', sa.Column('respons', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orgs_table', type_='foreignkey')
    op.create_foreign_key('orgs_table_ibfk_2', 'orgs_table', 'users_table', ['respons'], ['id'])
    op.drop_column('orgs_table', 'responsavel_id')
    # ### end Alembic commands ###
