"""visib

Revision ID: dba00936da75
Revises: b59300f50c40
Create Date: 2020-07-06 14:19:26.490865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba00936da75'
down_revision = 'b59300f50c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_table', sa.Column('visibilidade', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs_table', 'visibilidade')
    # ### end Alembic commands ###
