"""avatar

Revision ID: fddacf80ed28
Revises: 41ce8db27f71
Create Date: 2020-07-03 18:31:41.099047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fddacf80ed28'
down_revision = '41ce8db27f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icons_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'icons_table', 'users_table', ['user_id'], ['id'])
    op.drop_column('users_table', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('avatar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'icons_table', type_='foreignkey')
    op.drop_column('icons_table', 'user_id')
    # ### end Alembic commands ###
