"""org respons

Revision ID: fde401d2733c
Revises: 6801e377b843
Create Date: 2020-07-06 20:22:31.236221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fde401d2733c'
down_revision = '6801e377b843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_table', sa.Column('respons', sa.Integer(), nullable=True))
    op.drop_constraint('orgs_table_ibfk_2', 'orgs_table', type_='foreignkey')
    op.create_foreign_key(None, 'orgs_table', 'users_table', ['respons'], ['id'])
    op.drop_column('orgs_table', 'responsavel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_table', sa.Column('responsavel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orgs_table', type_='foreignkey')
    op.create_foreign_key('orgs_table_ibfk_2', 'orgs_table', 'users_table', ['responsavel'], ['id'])
    op.drop_column('orgs_table', 'respons')
    # ### end Alembic commands ###
