"""Etapas

Revision ID: 41ed946796c3
Revises: c9799125e61c
Create Date: 2020-11-24 17:34:28.968108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41ed946796c3'
down_revision = 'c9799125e61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapas_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=True),
    sa.Column('body', sa.Text(length=5000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('visibilidade', sa.String(length=32), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proj_id'], ['projs_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_table('etapas_table')
    # ### end Alembic commands ###
