"""inicial

Revision ID: 602aeaf85545
Revises: 
Create Date: 2020-11-18 16:41:45.029929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '602aeaf85545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('users_table', sa.Column('ano', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('cep', sa.String(length=32), nullable=True))
    op.add_column('users_table', sa.Column('cidade', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('dia', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('endereco1', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('endereco2', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('endereco3', sa.String(length=128), nullable=True))
    op.add_column('users_table', sa.Column('estado', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('genero', sa.String(length=32), nullable=True))
    op.add_column('users_table', sa.Column('mes', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('pais', sa.String(length=64), nullable=True))
    op.add_column('users_table', sa.Column('sobre_mim', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_table_genero'), 'users_table', ['genero'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_table_genero'), table_name='users_table')
    op.drop_column('users_table', 'sobre_mim')
    op.drop_column('users_table', 'pais')
    op.drop_column('users_table', 'mes')
    op.drop_column('users_table', 'genero')
    op.drop_column('users_table', 'estado')
    op.drop_column('users_table', 'endereco3')
    op.drop_column('users_table', 'endereco2')
    op.drop_column('users_table', 'endereco1')
    op.drop_column('users_table', 'dia')
    op.drop_column('users_table', 'cidade')
    op.drop_column('users_table', 'cep')
    op.drop_column('users_table', 'ano')
    op.alter_column('OrgsProjs', 'proj_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('OrgsProjs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
